- name: Build full settings for main.cf
  set_fact:
    postfix_main_full: '{{ postfix_main_defaults | combine(postfix_main) }}'

- name: Manage settings in main.cf
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^{{ item.key }}\s*=.*'
    line: "\
      {{ item.key }} = \
      {% if item.value == True %}{# noqa 601 #}\
      yes\
      {% elif item.value == False %}{# noqa 601 #}\
      no\
      {% else %}\
      {{ item.value }}\
      {% endif %}"
  with_dict: '{{ postfix_main_full }}'
  notify: reload postfix

- name: Configure mailname
  copy:
    dest: /etc/mailname
    content: |
      {{ postfix_main_full.myorigin }}
    mode: '0644'
  when: ansible_os_family == 'Debian'

- block:
    - name: Manage /etc/aliases
      lineinfile:
        path: /etc/aliases
        regexp: '^{{ item.key }}\s*=.*'
        line: '{{ item.key }}: {{ item.value }}'
      with_dict: '{{ postfix_aliases }}'
      register: aliases

    - name: Update /etc/aliases map
      command: newaliases
      when: aliases.changed

- name: Manage Postfix maps
  include_tasks: map.yml
  with_dict: '{{ postfix_maps }}'

- name: Check Postfix config
  command: postfix check
  changed_when: false
