- name: Manage Postfix map {{ item.key }}
  copy:
    dest: '{{ item.key }}'
    mode: 0600
    content: |
      # Managed by Ansible
      {% for line in item.value -%}
      {{ line }}
      {% endfor -%}

- import_tasks: map-update.yml
  vars:
    _postmap_file: '{{ item.key }}'
